### ISSUE TITLE
Publish Checklist

### ISSUE THREAD

**Issue by ashepherd** [ashepherd/alan-porter-music#11]
- [ ] Setup CNAME
    - [ ] configure at domain registry
    - [ ] edit config yaml site url
    - [ ] setup CNAME file
- [ ] Alan Register for formbold & update contact form submit URL
- [ ] Signup for Google Analytics
    - [ ] edit config.yaml
- [ ] Register Sitemap
